add_newline = true
command_timeout = 1000

format = """
[┌─](bold green)$username$hostname$directory$git_branch$git_status$git_state
[└─](bold green)$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bold purple"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "bold yellow"

[nodejs]
format = "via [$symbol($version)]($style) "
symbol = " "

[python]
format = "via [$symbol$version]($style) "
symbol = " "

[rust]
format = "via [$symbol($version)]($style) "
symbol = " "

[java]
format = "via [$symbol($version)]($style) "
symbol = " "

[elixir]
format = "via [$symbol$version]($style) "
symbol = " "

[gcloud]
disabled = true

[docker_context]
disabled = true